apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 50Mi
  volumeMode: Block
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # Only one node can use this
    # - ReadOnlyMany # Not available for hostPath
    # - ReadWriteMany # Not available for hostPath
  hostPath:
    path: /data
    type: DirectoryOrCreate